create database citizen_db;

use citizen_db;

CREATE TABLE Citizen (
SSN VARCHAR(11) PRIMARY KEY, Name VARCHAR(255) NOT NULL, DOB DATE NOT NULL,
CitizenshipStatus VARCHAR(50) NOT NULL );

CREATE TABLE Employment (
EmploymentID INT AUTO_INCREMENT PRIMARY KEY, 
SSN VARCHAR(11) NOT NULL,
EmployerID INT NOT NULL, JobTitle VARCHAR(100), StartDate DATE,
EndDate DATE,
FOREIGN KEY (SSN) REFERENCES Citizen(SSN) );

CREATE TABLE SocialSecurityRecord (
RecordID INT AUTO_INCREMENT PRIMARY KEY, SSN VARCHAR(11) NOT NULL,
Contributions DECIMAL(10, 2) NOT NULL, FOREIGN KEY (SSN) REFERENCES Citizen(SSN),
Benefits DECIMAL(15, 2) NOT NULL DEFAULT 0.00
);


CREATE TABLE TaxReturn (
ReturnID INT AUTO_INCREMENT PRIMARY KEY, 
SSN VARCHAR(11) NOT NULL,
Max_Income DECIMAL(15, 2) NOT NULL, 
Tax_Paid DECIMAL(15, 2) NOT NULL, 
Year INT NOT NULL,
FOREIGN KEY (SSN) REFERENCES Citizen(SSN),
UNIQUE (SSN, Year) -- Ensure only one tax return per SSN per year 
);


CREATE TABLE Address (
AddressID INT AUTO_INCREMENT PRIMARY KEY, SSN VARCHAR(11) NOT NULL,
City VARCHAR(100) NOT NULL, State VARCHAR(100) NOT NULL, ZIP VARCHAR(10) NOT NULL,
FOREIGN KEY (SSN) REFERENCES Citizen(SSN) );



 ALTER TABLE Address ADD CONSTRAINT fk_address_citizen FOREIGN KEY (SSN) REFERENCES Citizen(SSN);

CREATE TABLE TaxAuthority (
AuthorityID INT AUTO_INCREMENT PRIMARY KEY, 
Name VARCHAR(255) NOT NULL,
Region VARCHAR(255) NOT NULL ); 



ALTER TABLE TaxReturn ADD COLUMN AuthorityID INT;


ALTER TABLE TaxReturn
ADD CONSTRAINT fk_taxreturn_taxauthority FOREIGN KEY (AuthorityID)
REFERENCES TaxAuthority(AuthorityID);
